apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shoe
  template:
    metadata:
      labels:
        app: shoe
    spec:
      containers:
      - name: shoe
        image: shoe:1.0
        ports:
        - containerPort: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: shoe
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 1001
      nodePort: 30082
  selector:
    app: shoe
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: shoe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoe
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
