apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: offers
  template:
    metadata:
      labels:
        app: offers
    spec:
      containers:
      - name: offers
        image: offers:1.0
        ports:
        - containerPort: 1002
---
apiVersion: v1
kind: Service
metadata:
  name: offers
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 1002
      nodePort: 30083
  selector:
    app: offers
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: offers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: offers
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
